version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command:
            #docker build -t nodejsdemoapp1 -t barikahshafqat/nodejsdemoapp1:latest
            #echo $DOCKER_PASSWORD | docker login -u barikahshafqat/nodejsdemoapp1 --password-stdin
            #docker push barikahshafqat/nodejsdemoapp1:latest

            # Build the Docker image
            docker build -t nodejsdemoapp1 .

            # Login to Docker Hub
            echo $DOCKER_PASSWORD | docker login -u barikahshafqat --password-stdin

            # Tag the image
            docker tag nodejsdemoapp1 barikahshafqat/nodejsdemoapp1:latest
            
            # Push the image to Docker Hub
            docker push barikahshafqat/nodejsdemoapp1:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
  
